# Background and foreground colors
background = #0e0e05
foreground = #d6c3d8

# Standard colors
palette = 0=#0e0e05
palette = 1=#857960
palette = 2=#787e65
palette = 3=#939670
palette = 4=#bb9ca4
palette = 5=#8e7c92
palette = 6=#989f87
palette = 7=#d6c3d8

# Bright colors
palette = 8=#666760
palette = 9=#aa9e7c
palette = 10=#9ba382
palette = 11=#b8bd8a
palette = 12=#c6a398
palette = 13=#b59fbb
palette = 14=#bdc6a6
palette = 15=#f0c7f8
