background            #0e0e05
foreground            #d6c3d8

# black
color0  #0e0e05
color8  #666760

# red
color1  #857960
color9  #aa9e7c

# green
color2  #787e65
color10 #9ba382

# yellow
color3  #939670
color11 #b8bd8a

# blue
color4  #bb9ca4
color12 #c6a398

# magenta
color5  #8e7c92
color13 #b59fbb

#cyan
color6  #989f87
color14 #bdc6a6

#white
color7  #d6c3d8
color15 #f0c7f8


