sensors:
  - hwmon: /sys/devices/platform/coretemp.0/hwmon/hwmon5
    indices: [1, 2, 3, 4, 5]

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0, 0,  55]
  - [2, 53, 60]
  - [3, 58, 65]
  - [4, 63, 72]
  - [5, 70, 78]
  - [6, 75, 85]
  - [7, 80, 95]
  - ["level auto", 90, 255]