#!/usr/bin/env bash
# =============================================================================
# extras/thinkfan.sh — Configure Thinkfan for ThinkPad T14 Gen 2
# =============================================================================

set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/../lib/helpers.sh"

section "Thinkfan"

# -----------------------------------------------------------------------------
# Install thinkfan packages via the tagged package list
# -----------------------------------------------------------------------------
if ! is_installed thinkfan; then
    msg "Installing thinkfan packages..."
    bash "$(dirname "${BASH_SOURCE[0]}")/../packaging/install-packages.sh" --tag thinkfan
fi

# -----------------------------------------------------------------------------
# Enable fan control via thinkpad_acpi
# -----------------------------------------------------------------------------
# Write persistent config for next boots
echo "options thinkpad_acpi fan_control=1" | \
    sudo tee /etc/modprobe.d/thinkpad_acpi.conf > /dev/null
ok "thinkpad_acpi: fan_control=1 written to modprobe.d"

# Reload the module cleanly with the active parameter
if lsmod | grep -q thinkpad_acpi; then
    sudo modprobe -r thinkpad_acpi 2>/dev/null || true
fi
sudo modprobe thinkpad_acpi fan_control=1 || true
ok "thinkpad_acpi module loaded with fan_control=1"

if [[ ! -f /proc/acpi/ibm/fan ]]; then
    die "/proc/acpi/ibm/fan not found — thinkpad_acpi may not support fan control on this machine"
fi

# -----------------------------------------------------------------------------
# Detect hwmon path dynamically (hwmon index can vary between boots/installs)
# -----------------------------------------------------------------------------
HWMON_PATH=""
for dir in /sys/devices/platform/coretemp.0/hwmon/hwmon*; do
    if [[ -d "$dir" ]]; then
        HWMON_PATH="$dir"
        break
    fi
done

if [[ -z "$HWMON_PATH" ]]; then
    die "coretemp hwmon path not found — is lm_sensors loaded? Run: sudo systemctl start lm_sensors"
fi

INDICES=()
for f in "$HWMON_PATH"/temp*_input; do
    [[ -f "$f" ]] || continue
    idx="${f##*/temp}"
    idx="${idx%%_*}"
    INDICES+=("$idx")
done

if [[ ${#INDICES[@]} -eq 0 ]]; then
    die "No temp*_input sensors found under $HWMON_PATH"
fi

INDICES_STR=$(printf '%s, ' "${INDICES[@]}")
INDICES_STR="[${INDICES_STR%, }]"

ok "Detected hwmon path: $HWMON_PATH (indices: $INDICES_STR)"

# -----------------------------------------------------------------------------
# Generate /etc/thinkfan.conf
# -----------------------------------------------------------------------------
SPICE_DIR="${SPICE_DIR:-$HOME/spice}"
CONF_SRC="$SPICE_DIR/system/thinkfan/thinkfan.conf"

if [[ -f "$CONF_SRC" ]]; then
    sudo cp "$CONF_SRC" /etc/thinkfan.conf
    sudo sed -i -E "s|/sys/devices/platform/coretemp\.0/hwmon/hwmon[0-9]+|${HWMON_PATH}|" /etc/thinkfan.conf
    ok "thinkfan.conf installed from spice repo (hwmon path patched to $HWMON_PATH)"
else
    warn "thinkfan.conf not found at $CONF_SRC — generating from detected hardware"

    sudo tee /etc/thinkfan.conf > /dev/null <<EOF
# Generated by spice/extras/thinkfan.sh
# Hardware: ThinkPad T14 Gen 2i ($(uname -r))
# Detected: $HWMON_PATH

sensors:
  - hwmon: $HWMON_PATH
    indices: $INDICES_STR

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0,           0,  55]
  - [2,          53,  60]
  - [3,          58,  65]
  - [4,          63,  72]
  - [5,          70,  78]
  - [6,          75,  85]
  - [7,          80,  95]
  - ["level auto", 90, 255]
EOF

    ok "thinkfan.conf generated at /etc/thinkfan.conf"
fi

# -----------------------------------------------------------------------------
# Deploy hwmon auto-fix service (runs on every boot before thinkfan)
# -----------------------------------------------------------------------------
section "Deploying hwmon auto-fix service"

FIX_SCRIPT_SRC="$SPICE_DIR/system/thinkfan/fix-thinkfan-hwmon.sh"
FIX_UNIT_SRC="$SPICE_DIR/system/thinkfan/thinkfan-hwmon-fix.service"

if [[ -f "$FIX_SCRIPT_SRC" && -f "$FIX_UNIT_SRC" ]]; then
    sudo install -Dm755 "$FIX_SCRIPT_SRC" /usr/local/bin/fix-thinkfan-hwmon.sh
    sudo install -Dm644 "$FIX_UNIT_SRC" /etc/systemd/system/thinkfan-hwmon-fix.service

    sudo systemctl daemon-reload
    sudo systemctl enable thinkfan-hwmon-fix.service
    ok "thinkfan-hwmon-fix.service installed and enabled"
else
    warn "hwmon-fix files not found in spice repo — hwmon index changes across reboots won't be auto-corrected"
    warn "  expected: $FIX_SCRIPT_SRC"
    warn "  expected: $FIX_UNIT_SRC"
fi

# Restart the service immediately to apply configurations
sudo systemctl daemon-reload
sudo systemctl enable thinkfan.service && ok "thinkfan.service enabled" || warn "Failed to enable thinkfan.service"
sudo systemctl restart thinkfan.service || true

ok "Thinkfan setup complete — service restarted"
