[colors]
[colors.primary]
background = "#000b01"
foreground = "#d2dcc3"

[colors.normal]
black   = "#000b01"
red     = "#6e8d6c"
green   = "#85a27f"
yellow  = "#a3ae83"
blue    = "#579789"
magenta = "#609d8f"
cyan    = "#6aae9e"
white   = "#d2dcc3"

[colors.bright]
black   = "#5a5f5a"
red     = "#8fb488"
green   = "#a7ca9c"
yellow  = "#c6d49b"
blue    = "#75beac"
magenta = "#7fc5b2"
cyan    = "#89d6c1"
white   = "#d9eeb4"

[colors.cursor]
text   = "#000b01"
cursor = "#d2dcc3"
