background            #000b01
foreground            #d2dcc3

# black
color0  #000b01
color8  #5a5f5a

# red
color1  #6e8d6c
color9  #8fb488

# green
color2  #85a27f
color10 #a7ca9c

# yellow
color3  #a3ae83
color11 #c6d49b

# blue
color4  #579789
color12 #75beac

# magenta
color5  #609d8f
color13 #7fc5b2

#cyan
color6  #6aae9e
color14 #89d6c1

#white
color7  #d2dcc3
color15 #d9eeb4


