// Generated by OmaPets. managed-id: omapets-agent-hook-v1
export const OmaPets = async ({ $ }) => {
  const emit = async event => { await $`/home/abr/.config/omarchy/plugins/omapets/bin/omapets-hook ${event} opencode < /dev/null`.quiet() }
  return {
    event: async ({ event }) => {
      if (event.type === "session.created") await emit("session-start")
      else if (event.type === "session.status" && event.properties?.status?.type === "busy") await emit("prompt")
      else if (event.type === "permission.asked") await emit("permission")
      else if (event.type === "session.idle") await emit("stop")
      else if (event.type === "session.error") await emit("error")
      else if (event.type === "session.deleted") await emit("session-end")
    },
    "tool.execute.before": async () => { await emit("tool-start") },
    "tool.execute.after": async () => { await emit("tool-end") },
  }
}
export default OmaPets
